doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      userrole: App\Doctrine\Types\UserRoleType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: "%kernel.project_dir%/src/Doctrine/Mapping"
        prefix: 'App\Entity'
        alias: App
        type: xml
